local_backend: true
backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "home"
    label: "Home"
    files:
      - name: "hero"
        label: "Hero Section"
        file: "data/home/hero.json"
        fields:
          - { label: "Judul", name: "judul", widget: "string" }
          - { label: "Deskripsi", name: "deskripsi", widget: "text" }
          - { label: "Hero Background", name: "hero_background", widget: "image" }
          - { label: "Hero Foreground", name: "hero_foreground", widget: "image" }

  - name: "blog"
    label: "Blog"
    folder: "data/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "select", options: ["Admin", "Tim Teknis"] }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "products"
    label: "Produk"
    folder: "data/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nama", name: "nama", widget: "string" }
      - { label: "Deskripsi", name: "deskripsi", widget: "text" }
      - { label: "Gambar", name: "gambar", widget: "image" }

  - name: "settings"
    label: "Pengaturan Web"
    files:
      - name: "social"
        label: "Social Media"
        file: "data/settings.json"
        fields:
          - name: "social_media"
            label: "Social Media List"
            widget: "list"
            fields:
              - { label: "Platform", name: "platform", widget: "select", options: ["facebook", "instagram", "tiktok", "whatsapp"] }
              - { label: "URL", name: "url", widget: "string" }
